import { Notification } from '../Models/Notification';

export const sampleNotifications: Notification[] = [
    {
        id: 1,
        title: 'Новая Задача',
        description: 'Добавлена новая задача "Задача" к событию "Событие"',
        dt_created: '2023-03-16 12:00:00',
        read: false,
        recipientId: 0,
        taskId: 1,
        eventId: 1,
    },
    {
        id: 2,
        title: 'Новая задача',
        description: 'Добавлена новая задача "Задача1" к событию "Событие1"',
        dt_created: '2023-03-16 11:00:00',
        read: false,
        recipientId: 0,
        taskId: 1,
        eventId: 1,
    },
    {
        id: 3,
        title: 'Новое событие',
        description: 'Добавлено новое событие "Событие3"',
        dt_created: '2023-03-15 10:00:00',
        read: true,
        recipientId: 0,
        taskId: 1,
        eventId: 1,
    },
    {
        id: 4,
        title: 'Файлы Прикреплены',
        description: 'К задаче "Задача3" прикреплены файлы 1.docx, file.pdf и prs.pptx',
        dt_created: '2023-03-16 15:00:00',
        read: false,
        recipientId: 0,
        taskId: 1,
        eventId: 1,
    },
    {
        id: 5,
        title: 'Новое уведомление',
        description: 'Проверьте задачу "Задача5"',
        dt_created: '2023-03-17 11:00:00',
        read: true,
        recipientId: 0,
        taskId: 1,
        eventId: 1,
    },
];
